export const qk = {
  health: ["health"] as const,
  notificationChannels: ["notification-channels"] as const,
  radarDestinations: ["radar-destinations"] as const,
  searches: ["searches"] as const,
  search: (id: string) => ["searches", id] as const,
  flights: (id: string) => ["searches", id, "flights"] as const,
  prices: (id: string) => ["searches", id, "prices"] as const,
  analytics: (id: string) => ["searches", id, "analytics"] as const,
  recommendations: (id: string) => ["searches", id, "recommendations"] as const,
  advice: (id: string) => ["searches", id, "advice"] as const,
  events: (id: string) => ["searches", id, "events"] as const,
  notifications: (id: string) => ["searches", id, "notifications"] as const,
  alerts: (searchId?: string) => ["alerts", searchId ?? "all"] as const,
};
